# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
